services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest-rootless
    restart: always
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
      # Please consider allowing analytics to help us improve Homebox (basic computer information, no personal data)
      - HBOX_OPTIONS_ALLOW_ANALYTICS=true
    volumes:
      - /home/mnemosyne/app-datahomebox:/data/
    ports:
      - 3100:7745
