# Can be enhanced with an additional compose file
# See also https://docs.docker.com/compose/production/#modify-your-compose-file-for-production

services:
  radicale:
    image: tomsquest/docker-radicale
    container_name: radicale
    ports:
      - 5232:5232
    init: true
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - CHOWN
      - KILL
    deploy:
      resources:
        limits:
          memory: 256M
          pids: 50
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 30s
      retries: 3
    restart: unless-stopped
    volumes:
      - /home/mnemosyne/app-data/radicale/data:/data
      - /home/mnemosyne/app-data/radicale/config:/config:ro
    networks:
      traefik:
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      # HTTP
      traefik.http.routers.radicale-http.rule: Host(`calendar.apps.husovich.com`)
      traefik.http.routers.radicale-http.entrypoints: http
      traefik.http.routers.radicale-http.service: radicale
      traefik.http.routers.radicale-http.middlewares: redirect-https
      # HTTP Redirect
      traefik.http.middlewares.redirect-https.redirectScheme.scheme: https
      traefik.http.middlewares.redirect-https.redirectScheme.permanent: true
      # HTTPS
      traefik.http.routers.radicale-https.rule: Host(`calendar.apps.husovich.com`)
      traefik.http.routers.radicale-https.entrypoints: https
      traefik.http.routers.radicale-https.service: radicale
      traefik.http.routers.radical-https.tls: true
      traefik.http.routers.radicale-https.tls.certresolver: myresolver
      # Load Balancer      
      traefik.http.services.radicale.loadbalancer.server.port: 5232

networks:
  traefik:
    external: true
